import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components";
import Link from "next/link";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kike's Home Page",
  description: "Generated by my Hands bro",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col">
          <Navbar />
          {/* <h2 className="text-4xl bold">Main Layout</h2> */}
          <Link href={"/about"}>About</Link>
          {children}
        </div>
      </body>
    </html>
  );
}
